### PR TITLE
Fix Cache Duration Preference Being Ignored

### PR DESCRIPTION
**Pull request by jaspertandy**
As it stands, the cache duration preference is superseded by default parameters throughout this plugin. Since we call for this preference in the set method, it's redundant to set these as default parameters, and actually blocks the preference, leaving the preference itself inert. This PR fixes that.

There was also an issue in the cache logic (presumably because you never actually hit this code whilst developing!) whereby it would only extract the `%s` component from the interval. `->format('%s')` does not convert the duration to seconds, it simply extracts the seconds from your input. So if I use your default value of `PT15M`, the value here would be `0` since I didn't specify in seconds. Using this new code, I can specify `P1Y` and it gets converted and set correctly.

### CODE REVIEW

**Comment by cloudgrayau** [comment]
Agree, I just opened an issue about this - [#59 ](https://github.com/dukt/videos/issues/59)

**Review by cloudgrayau — CHANGES_REQUESTED** [review]
I'd change this to simply use the Craft helper though.

```
$expire = VideosPlugin::$plugin->getSettings()->cacheDuration;
$expire = new DateInterval($expire);
$expire = \craft\helpers\DateTimeHelper::intervalToSeconds($expire);
```

**Comment by jaspertandy** [comment]
I didn't know you could do that `intervalToSeconds` thing - I'll change that on my PR as it's much cleaner.

I think I've ended up running my fork and I'm glad I did because this PR has been ignored for a month.

**Comment by cloudgrayau** [comment]
Cheers! I might have to run your fork too. I need these changes on a live site and the developer appears to be MIA.

It is frustrating when developers go MIA on plugins that they expect you to pay for...

**Comment by jaspertandy** [comment]
I'm not sure if you get notified of new commits or not (not that familiar with github/PRs so sorry if this bombards you with email!) but I've updated this PR and master in my fork with your helper suggestion.

**Comment by philperusse** [comment]
For anyone landing here before a fix is deployed, here's a workaround: 

Make sure you only use seconds in your DateInterval config setting.
```php
'cacheDuration' => 'PT31536000S', // 1 year in seconds
```

**Pull request merged**
